name = "ğŸš€ Adaptive Performance Tweaks: Items ğŸ—‘ï¸"
filename = "adaptive_performance_tweaks_items_1.18.1-0.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3612/839/adaptive_performance_tweaks_items_1.18.1-0.2.1.jar"
hash-format = "murmur2"
hash = "4127992114"

[update]
[update.curseforge]
file-id = 3612839
project-id = 561439
