name = "ğŸš€ Adaptive Performance Tweaks: Items ğŸ—‘ï¸"
filename = "adaptive_performance_tweaks_items_1.18.1-0.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3592/596/adaptive_performance_tweaks_items_1.18.1-0.2.0.jar"
hash-format = "murmur2"
hash = "1578838167"

[update]
[update.curseforge]
file-id = 3592596
project-id = 561439
