name = "ğŸš€ Adaptive Performance Tweaks: Core âš™ï¸"
filename = "adaptive_performance_tweaks_core_1.18.1-0.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3592/591/adaptive_performance_tweaks_core_1.18.1-0.2.0.jar"
hash-format = "murmur2"
hash = "1834881447"

[update]
[update.curseforge]
file-id = 3592591
project-id = 561087
