name = "ğŸš€ Adaptive Performance Tweaks: Core âš™ï¸"
filename = "adaptive_performance_tweaks_core_1.18.1-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3620/688/adaptive_performance_tweaks_core_1.18.1-1.0.0.jar"
hash-format = "murmur2"
hash = "1313290028"

[update]
[update.curseforge]
file-id = 3620688
project-id = 561087
