name = "ğŸš€ Adaptive Performance Tweaks: Items ğŸ—‘ï¸"
filename = "adaptive_performance_tweaks_items_1.18.1-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3620/702/adaptive_performance_tweaks_items_1.18.1-1.0.0.jar"
hash-format = "murmur2"
hash = "3494959082"

[update]
[update.curseforge]
file-id = 3620702
project-id = 561439
